# Generated by Django 2.1.3 on 2018-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiheaders',
            field=models.CharField(max_length=200, null=True, verbose_name='headers'),
        ),
    ]
