# Generated by Django 2.1.3 on 2018-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20181204_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='apitestfunc',
            field=models.CharField(max_length=20, null=True, verbose_name='函数'),
        ),
    ]
