# Generated by Django 2.1.3 on 2018-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_apis_apitestfunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitest',
            name='apitestfunc',
            field=models.CharField(max_length=20, null=True, verbose_name='函数'),
        ),
    ]
