# Generated by Django 2.1.3 on 2018-12-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_apitest_apitestfunc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='apitestfunc',
            new_name='apifunc',
        ),
    ]
