# Generated by Django 2.1.2 on 2018-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(max_length=20, null='true', verbose_name='报告类型'),
            preserve_default='true',
        ),
    ]
