# Generated by Django 2.1.2 on 2018-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('api', 'api'), ('ui', 'ui'), ('app', 'app'), ('other', 'other')], default='api', max_length=20, null=True, verbose_name='报告类型'),
        ),
    ]
